// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SLCDM.Persistence;

#nullable disable

namespace SLCDM.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260831205422_AddIdSedeUbicacion")]
    partial class AddIdSedeUbicacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SLCDM.Domain.Entities.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_activo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostoAdquisicion")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("costo_adquisicion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("date")
                        .HasColumnName("fecha_compra");

                    b.Property<DateTime>("FechaVencimientoGarantia")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento_garantia");

                    b.Property<int>("IdCategoriaActivo")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria_activo");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<int?>("IdUbicacion")
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Moneda")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("moneda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("numero_factura");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("numero_serie");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaActivo");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdUbicacion");

                    b.HasIndex("NumeroSerie");

                    b.ToTable("activo", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_area");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.Property<int>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdSede");

                    b.ToTable("area", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Asignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asignacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activa");

                    b.Property<DateTime?>("DocumentoPdfGenerardoEn")
                        .HasColumnType("datetime2")
                        .HasColumnName("documento_pdf_generado_en");

                    b.Property<string>("DocumentoPdfUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("documento_pdf_url");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_asignacion");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_devolucion");

                    b.Property<DateTime?>("FechaFirmaEntrega")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_firma_entrega");

                    b.Property<byte[]>("FirmaDevolucion")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("firma_recibe");

                    b.Property<byte[]>("FirmaEntrega")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("firma_entrega");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int")
                        .HasColumnName("id_activo");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("int")
                        .HasColumnName("id_responsable");

                    b.Property<int>("IdTipoAsignacion")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_asignacion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdActivo")
                        .IsUnique()
                        .HasDatabaseName("ix_asignacion_activo_unica_activa")
                        .HasFilter("[activa] = 1");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdResponsable");

                    b.HasIndex("IdTipoAsignacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("asignacion", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Bitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_bitacora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entidad_afectada");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("InformacionAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("informacion_anterior");

                    b.Property<string>("InformacionNueva")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("informacion_nueva");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tipo_operacion");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("IdUsuario");

                    b.ToTable("bitacora", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.CategoriaActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("categoria_activo", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.DetalleActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_activo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BuenEstado")
                        .HasColumnType("bit")
                        .HasColumnName("buen_estado");

                    b.Property<bool>("Encontrado")
                        .HasColumnType("bit")
                        .HasColumnName("encontrado");

                    b.Property<DateTime>("FechaVerificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_verificacion");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int")
                        .HasColumnName("id_activo");

                    b.Property<int>("IdHistoricoInventario")
                        .HasColumnType("int")
                        .HasColumnName("id_historico_inventario");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("observaciones");

                    b.HasKey("Id");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdHistoricoInventario");

                    b.ToTable("detalle_activo", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("direccion");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.Property<string>("NitCodigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nit_codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("NitCodigo")
                        .IsUnique();

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("estado", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.HistorialActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial_activo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_hora");

                    b.Property<int?>("IdAsignacion")
                        .HasColumnType("int")
                        .HasColumnName("id_asignacion");

                    b.Property<int?>("IdDetalleActivo")
                        .HasColumnType("int")
                        .HasColumnName("id_detalle_activo");

                    b.Property<string>("InformacionAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("informacion_anterior");

                    b.Property<string>("InformacionNueva")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("informacion_nueva");

                    b.Property<string>("TipoOperacion")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tipo_operacion");

                    b.HasKey("Id");

                    b.HasIndex("IdAsignacion");

                    b.HasIndex("IdDetalleActivo");

                    b.ToTable("historial_activo", null, t =>
                        {
                            t.HasCheckConstraint("ck_historial_activo_una_sola_fuente", "([id_asignacion] IS NOT NULL AND [id_detalle_activo] IS NULL) OR ([id_asignacion] IS NULL AND [id_detalle_activo] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.HistoricoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historico_inventario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Cerrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("cerrado");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Responsable")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("responsable");

                    b.HasKey("Id");

                    b.HasIndex("IdSede");

                    b.ToTable("historico_inventario", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("codigo_iso2");

                    b.Property<string>("CodigoIso3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("codigo_iso3");

                    b.Property<string>("CodigoTelefonico")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("codigo_telefonico");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("CodigoIso2")
                        .IsUnique();

                    b.HasIndex("CodigoIso3")
                        .IsUnique();

                    b.ToTable("pais", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreContacto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_contacto");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("Nit");

                    b.ToTable("proveedor", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Responsable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_responsable");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.Property<int>("IdArea")
                        .HasColumnType("int")
                        .HasColumnName("id_area");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("IdArea");

                    b.ToTable("responsable", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("direccion");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdPais");

                    b.ToTable("sede", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.TipoAsignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_asignacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("tipo_asignacion", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ubicacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.Property<int>("IdSede")
                        .HasColumnType("int")
                        .HasColumnName("id_sede");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitud");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitud");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdSede");

                    b.HasIndex("Nombre");

                    b.ToTable("ubicacion", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("Habilitado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("habilitado");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Activo", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.CategoriaActivo", "CategoriaActivo")
                        .WithMany()
                        .HasForeignKey("IdCategoriaActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SLCDM.Domain.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SLCDM.Domain.Entities.Ubicacion", "Ubicacion")
                        .WithMany()
                        .HasForeignKey("IdUbicacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaActivo");

                    b.Navigation("Proveedor");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Area", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.Sede", null)
                        .WithMany()
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Asignacion", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SLCDM.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SLCDM.Domain.Entities.Responsable", "Responsable")
                        .WithMany()
                        .HasForeignKey("IdResponsable")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SLCDM.Domain.Entities.TipoAsignacion", "TipoAsignacion")
                        .WithMany()
                        .HasForeignKey("IdTipoAsignacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SLCDM.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Estado");

                    b.Navigation("Responsable");

                    b.Navigation("TipoAsignacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Bitacora", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.DetalleActivo", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SLCDM.Domain.Entities.HistoricoInventario", "HistoricoInventario")
                        .WithMany()
                        .HasForeignKey("IdHistoricoInventario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("HistoricoInventario");
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.HistorialActivo", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.Asignacion", "Asignacion")
                        .WithMany()
                        .HasForeignKey("IdAsignacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SLCDM.Domain.Entities.DetalleActivo", "DetalleActivo")
                        .WithMany()
                        .HasForeignKey("IdDetalleActivo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asignacion");

                    b.Navigation("DetalleActivo");
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.HistoricoInventario", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Proveedor", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Responsable", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Sede", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SLCDM.Domain.Entities.Pais", null)
                        .WithMany()
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Ubicacion", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.Sede", null)
                        .WithMany()
                        .HasForeignKey("IdSede")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SLCDM.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SLCDM.Domain.Entities.Empresa", null)
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
